### ISSUE TITLE
pressing any key crashes the editor on linux

### ISSUE THREAD

**Issue by youngnix** [focus-editor/focus#481]
**Describe the bug**
Pressing any key will crash the editor on the Linux build.

```
xkbcommon: loaded libxkbcommon.so.0
WAYLAND: loaded libwayland-client.so.0
WAYLAND: loaded libwayland-egl.so.1
WAYLAND: loaded libwayland-cursor.so.0
Started watching external directory '/home/user/.config/focus-editor'
EGL: loaded libEGL.so.1
SIGFPE: The program crashed because of an integer division by zero error.
./focus-linux(__procedure_7000003dd+0x38a) [0x8b477a]
/usr/lib/libffi.so.8(+0x7596) [0x7234b7538596]
/usr/lib/libffi.so.8(+0x400e) [0x7234b753500e]
/usr/lib/libffi.so.8(ffi_call+0x123) [0x7234b7537bd3]
/usr/lib/libwayland-client.so.0(+0x48b0) [0x7234b75408b0]
/usr/lib/libwayland-client.so.0(+0x5139) [0x7234b7541139]
/usr/lib/libwayland-client.so.0(wl_display_dispatch_queue_pending+0x73) [0x7234b7541553]
./focus-linux(wl_event_loop_step_7000003ef+0x1a7) [0x8abbb7]
./focus-linux(wl_wait_for_events_7000003f0+0x82) [0x8a7932]
./focus-linux(__program_main+0x3ec6) [0x88e676]
./focus-linux(main+0x48) [0x8d1218]
/usr/lib/libc.so.6(+0x25e08) [0x7234b7af3e08]
/usr/lib/libc.so.6(__libc_start_main+0x8c) [0x7234b7af3ecc]
./focus-linux(_start+0x2a) [0x8de03a]
```

**To Reproduce**
Run focus-linux and press literally any key on the keyboard.

**Additional context**
I'm on Arch Linux on the sway WM.

**Comment by focus-editor** [comment]
What editor version are you running?

**Comment by youngnix** [comment]
It will crash on a key press from 0.3.6 and up. 0.3.5 was not rendering correctly and gave me a floating point exception, but it wasn't related to key presses.

**Comment by ileonte** [comment]
Can you please try the latest nightly build from here: https://ileonte.dev/focus-builds/Linux/nightly/ ?

If that still crashes it would be of great help if you could generate a backtrace by running:
```
gdb -ex 'run' -ex 'bt' -ex 'quit' --args /path/to/focus-linux
```
and posting the output of that here.

**Comment by youngnix** [comment]
> Can you please try the latest nightly build from here: https://ileonte.dev/focus-builds/Linux/nightly/ ?
> 
> If that still crashes it would be of great help if you could generate a backtrace by running:
> 
> ```
> gdb -ex 'set pagination off' -ex 'set confirm off' -ex 'run' -ex 'bt -full' -ex 'quit' --args /path/to/focus-linux
> ```
> 
> and posting the output of that here.

```
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from focus-linux-nightly-9990b06...
Starting program: /home/andrei/Downloads/focus-linux-nightly-9990b06 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
xkbcommon: loaded libxkbcommon.so.0
WAYLAND: loaded libwayland-client.so.0
WAYLAND: loaded libwayland-egl.so.1
WAYLAND: loaded libwayland-cursor.so.0
Started watching external directory '/home/andrei/.config/focus-editor'
[New Thread 0x7fffd6fff6c0 (LWP 17245)]
EGL: loaded libEGL.so.1
[New Thread 0x7fffc94be6c0 (LWP 17247)]
[New Thread 0x7fffc8cbd6c0 (LWP 17248)]
[New Thread 0x7fffc3fff6c0 (LWP 17250)]
[Thread 0x7fffc3fff6c0 (LWP 17250) exited]
[New Thread 0x7fffc3fff6c0 (LWP 17251)]
[Thread 0x7fffc3fff6c0 (LWP 17251) exited]
[New Thread 0x7fffc3fff6c0 (LWP 17252)]

Thread 1 "focus-linux-nig" received signal SIGFPE, Arithmetic exception.
0x0000000000900168 in __procedure_1100000365 (data=<optimized out>, self=<optimized out>, serial=53588, time=<optimized out>, key=29, state=1)
    at /build/modules/Linux_Display/ldw_input.jai:42
warning: 42	/build/modules/Linux_Display/ldw_input.jai: Aucun fichier ou dossier de ce nom
#0  0x0000000000900168 in __procedure_1100000365 (data=<optimized out>, self=<optimized out>, serial=53588, time=<optimized out>, key=29, state=1)
    at /build/modules/Linux_Display/ldw_input.jai:42
        rate = <optimized out>
        d = 0x9ee7e0 <_global_data_base+22496>
        ctx = {base = {context_info = 0x26c710 <_type_table_section+110496>, thread_index = 0, allocator = {
              proc = 0x6e24d0 <allocator_proc_b00000330>, data = 0x0}, logger = 0x6e3b60 <runtime_support_default_logger_30000022d>, 
            logger_data = 0x0, log_source_identifier = 0, log_level = NORMAL, temporary_storage = 0x0, stack_trace = 0x7fffffffbef0, 
            assertion_failed = 0x748720 <runtime_support_assertion_failed_30000022b>, handling_assertion_failure = false, 
            program_print_plugin = 0x0}, current_editor_id = -1, simp = 0x0, print_style = {default_format_int = {formatter = {value = {type = 0x0, 
                  value_pointer = 0x0}}, base = 10, minimum_digits = 1, padding = 48 '0', digits_per_comma = 0, comma_string = {count = 0, 
                data = 0x0}}, default_format_float = {formatter = {value = {type = 0x0, value_pointer = 0x0}}, width = -1, trailing_width = -1, 
              zero_removal = YES, mode = DECIMAL, thousand_separators = false, thousand_separator_character = 44 ',', 
              decimal_separator_character = 46 '.', exponent_character = 101 'e', positive_number_prefix = NONE}, default_format_struct = {
              formatter = {value = {type = 0x0, value_pointer = 0x0}}, draw_type_name = false, use_long_form_if_more_than_this_many_members = 5, 
              separator_between_name_and_value = {count = 3, data = 0x4bbee7 <_literals+1634023> " = "}, short_form_separator_between_fields = {
                count = 2, data = 0x4bbbbf <_literals+1633215> ", "}, long_form_separator_between_fields = {count = 2, 
                data = 0x4bbeeb <_literals+1634027> "; "}, begin_string = {count = 1, data = 0x4bbeee <_literals+1634030> "{"}, end_string = {
                count = 1, data = 0x4bbef0 <_literals+1634032> "}"}, indentation_width = 4, use_newlines_if_long_form = false}, 
            default_format_array = {formatter = {value = {type = 0x0, value_pointer = 0x0}}, separator = {count = 2, 
                data = 0x4bbbbf <_literals+1633215> ", "}, begin_string = {count = 1, data = 0x4bbef2 <_literals+1634034> "["}, end_string = {
                count = 1, data = 0x4bbef4 <_literals+1634036> "]"}, printing_stopped_early_string = {count = 3, 
                data = 0x4bbef6 <_literals+1634038> "..."}, draw_separator_after_last_element = false, 
              stop_printing_after_this_many_elements = 100}, default_format_absolute_pointer = {formatter = {value = {type = 0x0, 
                  value_pointer = 0x0}}, base = 16, minimum_digits = 1, padding = 48 '0', digits_per_comma = 4, comma_string = {count = 1, 
                data = 0x4bc0e7 <_literals+1634535> "_"}}, struct_printer = 0x0, struct_printer_data = 0x0, indentation_depth = 0, 
            log_runtime_errors = true}}
#1  0x00007ffff781c596 in ?? () from /usr/lib/libffi.so.8
No symbol table info available.
#2  0x00007ffff781900e in ?? () from /usr/lib/libffi.so.8
No symbol table info available.
#3  0x00007ffff781bbd3 in ffi_call () from /usr/lib/libffi.so.8
No symbol table info available.
#4  0x00007ffff78248b0 in ?? () from /usr/lib/libwayland-client.so.0
No symbol table info available.
#5  0x00007ffff7825139 in ?? () from /usr/lib/libwayland-client.so.0
No symbol table info available.
#6  0x00007ffff7825553 in wl_display_dispatch_queue_pending () from /usr/lib/libwayland-client.so.0
No symbol table info available.
#7  0x00000000008f7207 in wl_event_loop_step_1100000377 (context=..., display=0x9ee7e0 <_global_data_base+22496>, timeout=<optimized out>)
    at /build/modules/Linux_Display/ldw_input.jai:264
        dpy = 0xb02ea0
        dispatch_count = <optimized out>
        tev = false
        wlev = <optimized out>
#8  0x00000000008f5692 in wl_wait_for_events_1100000378 (context=..., display=0x9ee7e0 <_global_data_base+22496>)
    at /build/modules/Linux_Display/ldw_input.jai:275
No locals.
#9  0x00000000008da586 in __program_main (context=...) at /build/modules/Linux_Display/linux_display.jai:238
        bd = <optimized out>
        display = <optimized out>
        current_time = {low = 1693082996081704064, high = 771}
        num_text_input_events_to_ignore = <optimized out>
        window_has_focus = <optimized out>
        shift_key = {<No data fields>}
        args = <optimized out>
        window_resized = false
        projects_dir_existed = <optimized out>
#10 0x000000000091c8ee in __system_entry_point_30000023f (argc=<optimized out>, argv=<optimized out>) at /build/modules/Runtime_Support.jai:451
No locals.
```

Latest nightly build. It no longer crashes due to a key press, but due to a floating point exception.

**Comment by ileonte** [comment]
This should be fixed in the latest nightly: https://ileonte.dev/focus-builds/Linux/nightly/x86_64/focus-linux-nightly-81e4f65

**Comment by youngnix** [comment]
> This should be fixed in the latest nightly: https://ileonte.dev/focus-builds/Linux/nightly/x86_64/focus-linux-nightly-81e4f65

It is! Thank you for solving it so quickly.

**Comment by ileonte** [comment]
Thank you for reporting and testing!
